### ISSUE TITLE
Add polite handing of unknown schema

### ISSUE THREAD

**Issue by adnikiforov** [adnikiforov/iuliia-rb#7]
Right now it looks like that:

```
2.6.6 :002 > Iuliia::Schema['mvd']
Traceback (most recent call last):
        7: from bin/console:15:in `<main>'
        6: from (irb):2
        5: from (irb):2:in `rescue in irb_binding'
        4: from /Users/user/RubymineProjects/iuliia-rb/lib/iuliia/schema.rb:11:in `[]'
        3: from /Users/user/RubymineProjects/iuliia-rb/lib/iuliia/schema.rb:25:in `block in schemas'
        2: from /Users/user/RubymineProjects/iuliia-rb/lib/iuliia/schema.rb:29:in `load_schema'
        1: from /Users/user/RubymineProjects/iuliia-rb/lib/iuliia/schema.rb:29:in `read'
Errno::ENOENT (No such file or directory @ rb_sysopen - lib/schemas/mvd.json)
```

Better if we will return more polite and understandable error.

**Comment by adnikiforov** [comment]
Would be nice to have specs for that too.
